apiVersion: v1
kind: Service
metadata:
  name: deen-ops-service
  namespace: production
  labels:
    app.kubernetes.io/name: deen-ops-terminal
    app.kubernetes.io/part-of: deen-commerce-ops
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: deen-ops-terminal
  ports:
    - name: http-streamlit
      port: 8501
      targetPort: http-streamlit
      protocol: TCP
