"""Generate a runtime lock file from requirements.txt in a clean virtualenv."""

from __future__ import annotations

import argparse
import os
import subprocess
import sys
import tempfile
import venv
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = PROJECT_ROOT / "requirements.lock"
EXCLUDED_PACKAGES = ("pip==", "setuptools==", "wheel==")
RUNTIME_REQUIREMENTS = [
    "requirements.txt",
]


def _venv_python(venv_dir: Path) -> Path:
    if os.name == "nt":
        return venv_dir / "Scripts" / "python.exe"
    return venv_dir / "bin" / "python"


def _run(cmd: list[str], *, cwd: Path) -> str:
    result = subprocess.run(
        cmd,
        cwd=cwd,
        check=True,
        text=True,
        capture_output=True,
    )
    return result.stdout


def generate_lock_file(output_path: Path) -> None:
    with tempfile.TemporaryDirectory(prefix="deenops-lock-") as temp_dir:
        venv_dir = Path(temp_dir) / "venv"
        venv.EnvBuilder(with_pip=True, clear=True).create(venv_dir)
        python_path = _venv_python(venv_dir)

        _run(
            [str(python_path), "-m", "pip", "install", "--upgrade", "pip"],
            cwd=PROJECT_ROOT,
        )
        install_cmd = [str(python_path), "-m", "pip", "install"]
        for requirement_file in RUNTIME_REQUIREMENTS:
            install_cmd.extend(["-r", requirement_file])
        _run(install_cmd, cwd=PROJECT_ROOT)

        freeze_output = _run(
            [str(python_path), "-m", "pip", "freeze", "--all"],
            cwd=PROJECT_ROOT,
        ).splitlines()

    filtered_lines = [
        line
        for line in freeze_output
        if line and not line.startswith(EXCLUDED_PACKAGES)
    ]
    content = [
        "# Generated by scripts/generate_requirements_lock.py",
        f"# Python {sys.version_info.major}.{sys.version_info.minor}",
        "",
        *filtered_lines,
        "",
    ]
    output_path.write_text("\n".join(content), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        default=str(DEFAULT_OUTPUT),
        help="Lock file output path. Defaults to requirements.lock at the repo root.",
    )
    args = parser.parse_args()

    output_path = Path(args.output).resolve()
    generate_lock_file(output_path)
    print(f"Wrote lock file to {output_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
