[server]
port = 8501
headless = true
enableCORS = true
corsAllowedOrigins = [
    "https://ops.deencommerce.com",
    "http://localhost:8501",
    "http://192.168.68.103:8501",
    "http://103.7.248.247:8501",
]
allowedHosts = [
    "ops.deencommerce.com",
    "localhost",
    "127.0.0.1",
    "192.168.68.103",
    "103.7.248.247",
]
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false
