[server]
port = 8501
headless = true
enableCORS = false
enableXsrfProtection = true
maxUploadSize = 200
enableWebsocketCompression = true

[browser]
gatherUsageStats = false

[theme]
base = "dark"
primaryColor = "#10b981"
backgroundColor = "#090d16"
secondaryBackgroundColor = "#0f172a"
textColor = "#f8fafc"
font = "sans serif"
